#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fibs = {}
def fib(n):
	if n in fibs:
		return fibs[n]
	if n <= 1:
		return 1
	else:
		fibs[n] = fib(n-1) + fib(n-2)
		return fibs[n]

def main():
	fibs = []
	i = 0
	while True:
		n = fib(i)
		if n % 2 == 0:
			fibs.append(n)
		if n > 4*1000*1000:
			break
		i += 1
	#for f in fibs:
	#	print(f)
	print(sum(fibs))
if __name__ == '__main__':
	main()